/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionGroup: typeof import('./../components/ActionGroup/index.vue')['default']
    ActionItem: typeof import('./../components/ActionGroup/ActionItem.vue')['default']
    DialogForm: typeof import('./../components/DialogForm/index.vue')['default']
    DrawerForm: typeof import('./../components/DrawerForm/index.vue')['default']
    Page: typeof import('./../components/Page/index.vue')['default']
    ProTable: typeof import('./../components/ProTable/index.vue')['default']
    ProUpload: typeof import('./../components/ProUpload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
    WangEditor: typeof import('./../components/WangEditor/index.vue')['default']
  }
}
